#!/usr/bin/env python3
"""
Publish the latest case-study HTML reports to docs/ for GitHub Pages.

For every report in ``results/case_studies/*.html`` it keeps the most recent run
per (study, model), copies it into ``docs/``, and rewrites the auto-generated
block in ``docs/index.html`` (between the REPORTS:START / REPORTS:END markers)
with a card linking to each one. It also links every cross-model comparison page
(``docs/comparison_<study>.html``, written by ``scripts/compare_models.py``)
between the COMPARISONS:START / COMPARISONS:END markers.

Run directly to publish whatever reports already exist:

    python scripts/publish_reports.py

Usually invoked via ``make publish`` (which runs the studies first).
"""

from __future__ import annotations

import html
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results" / "case_studies"
DOCS = ROOT / "docs"
INDEX = DOCS / "index.html"

START = (
    "<!-- REPORTS:START (auto-generated by scripts/publish_reports.py — do not edit by hand) -->"
)
END = "<!-- REPORTS:END -->"
CMP_START = (
    "<!-- COMPARISONS:START "
    "(auto-generated by scripts/publish_reports.py — do not edit by hand) -->"
)
CMP_END = "<!-- COMPARISONS:END -->"

# Trailing timestamp produced by CaseStudyReporter: _YYYYMMDD_HHMMSS
_STAMP = re.compile(r"^(?P<key>.+)_(?P<stamp>\d{8}_\d{6})$")


def _latest_reports() -> dict[str, Path]:
    """Map each (study, model) key to its most recent HTML report."""
    latest: dict[str, tuple[str, Path]] = {}
    for path in RESULTS.glob("*.html"):
        m = _STAMP.match(path.stem)
        if not m:
            continue
        key, stamp = m.group("key"), m.group("stamp")
        if key not in latest or stamp > latest[key][0]:
            latest[key] = (stamp, path)
    return {key: path for key, (_, path) in latest.items()}


def _title(key: str) -> str:
    return key.replace("_", " ").replace("microsoft/", "").replace("/", " ").strip().title()


def _provider(key: str) -> str:
    """Badge provider dérivé du nom du run (heuristique)."""
    k = key.lower()
    if "claude" in k or "anthropic" in k:
        return "Anthropic"
    if "gpt" in k or "o1" in k or "o3" in k:
        return "OpenAI"
    if "groq" in k or "llama" in k or "mixtral" in k:
        return "Groq"
    return "Model"


def _card(key: str, filename: str) -> str:
    t = html.escape(_title(key))
    f = html.escape(filename)
    provider = html.escape(_provider(key))
    return (
        '      <div class="card">'
        f'<span class="tag">{provider}</span>'
        f"<h3>{t}</h3>"
        "<p>Baseline vs strategies — quality and real token cost.</p>"
        f'<a href="{f}">Open report &rarr;</a></div>'
    )


def _comparison_card(path: Path) -> str:
    """Card for a cross-model comparison page (docs/comparison_<study>.html)."""
    study = path.stem.removeprefix("comparison_")
    t = html.escape(_title(study))
    f = html.escape(path.name)
    return (
        '      <div class="card">'
        '<span class="tag">Cross-model</span>'
        f"<h3>{t}</h3>"
        "<p>One harness, several providers — baseline vs improvement strategy, "
        "with charts, per-difficulty breakdown and auto-generated findings.</p>"
        f'<a href="{f}">Open the comparison &rarr;</a></div>'
    )


def _inject(text: str, start: str, end: str, block: str, index: Path) -> str:
    """Replace the content between two markers with ``block``."""
    if start not in text or end not in text:
        raise SystemExit(f"Markers {start!r} not found in {index}; cannot inject.")
    return re.sub(
        re.escape(start) + r".*?" + re.escape(end),
        f"{start}\n{block}\n    {end}",
        text,
        flags=re.DOTALL,
    )


def _empty_block() -> str:
    return (
        '    <p class="lead" style="font-size:.92rem;">No published reports yet — run '
        "<code>make publish model=gpt-4o-mini</code> to generate trustworthy ones with the "
        "fixed scoring and pricing.</p>\n"
        '    <div class="btns" style="justify-content:flex-start;">\n'
        '      <a class="btn primary" '
        'href="https://github.com/MalekSnous/llm-diagnostic-framework#-case-studies">'
        "How to run the studies &rarr;</a>\n    </div>"
    )


def main() -> None:
    if not RESULTS.exists():
        print(f"No results directory at {RESULTS}; nothing to publish.")
        reports: dict[str, Path] = {}
    else:
        reports = _latest_reports()

    cards = []
    for key in sorted(reports):
        src = reports[key]
        dest = DOCS / src.name
        shutil.copy2(src, dest)
        cards.append(_card(key, src.name))
        print(f"published {src.name}")

    inner = "\n".join(cards)
    block = f'    <div class="grid">\n{inner}\n    </div>' if cards else _empty_block()

    comparisons = sorted(DOCS.glob("comparison_*.html"))
    cmp_cards = "\n".join(_comparison_card(p) for p in comparisons)
    cmp_block = (
        f'    <div class="grid">\n{cmp_cards}\n    </div>'
        if comparisons
        else '    <p class="lead" style="font-size:.92rem;">No comparison published yet — '
        "run <code>make benchmark</code> to generate one.</p>"
    )

    text = INDEX.read_text(encoding="utf-8")
    new = _inject(text, START, END, block, INDEX)
    new = _inject(new, CMP_START, CMP_END, cmp_block, INDEX)
    INDEX.write_text(new, encoding="utf-8")
    print(f"updated {INDEX} ({len(cards)} report card(s), {len(comparisons)} comparison card(s))")


if __name__ == "__main__":
    main()
