#!/usr/bin/env python3
"""
Publish the latest case-study HTML reports to docs/ for GitHub Pages.

For every report in ``results/case_studies/*.html`` it keeps the most recent run
per (study, model), copies it into ``docs/``, and rewrites the auto-generated
block in ``docs/index.html`` (between the REPORTS:START / REPORTS:END markers)
with a card linking to each one.

Run directly to publish whatever reports already exist:

    python scripts/publish_reports.py

Usually invoked via ``make publish`` (which runs the studies first).
"""

from __future__ import annotations

import html
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results" / "case_studies"
DOCS = ROOT / "docs"
INDEX = DOCS / "index.html"

START = (
    "<!-- REPORTS:START (auto-generated by scripts/publish_reports.py — do not edit by hand) -->"
)
END = "<!-- REPORTS:END -->"

# Trailing timestamp produced by CaseStudyReporter: _YYYYMMDD_HHMMSS
_STAMP = re.compile(r"^(?P<key>.+)_(?P<stamp>\d{8}_\d{6})$")


def _latest_reports() -> dict[str, Path]:
    """Map each (study, model) key to its most recent HTML report."""
    latest: dict[str, tuple[str, Path]] = {}
    for path in RESULTS.glob("*.html"):
        m = _STAMP.match(path.stem)
        if not m:
            continue
        key, stamp = m.group("key"), m.group("stamp")
        if key not in latest or stamp > latest[key][0]:
            latest[key] = (stamp, path)
    return {key: path for key, (_, path) in latest.items()}


def _title(key: str) -> str:
    return key.replace("_", " ").replace("microsoft/", "").replace("/", " ").strip().title()


def _card(title: str, filename: str) -> str:
    t = html.escape(title)
    f = html.escape(filename)
    return (
        '      <div class="card">'
        f"<h3>{t}</h3>"
        "<p>Baseline vs strategies — F1 and real token cost.</p>"
        f'<a href="{f}">Open report &rarr;</a></div>'
    )


def _empty_block() -> str:
    return (
        '    <p class="lead" style="font-size:.92rem;">No published reports yet — run '
        "<code>make publish model=gpt-4o-mini</code> to generate trustworthy ones with the "
        "fixed scoring and pricing.</p>\n"
        '    <div class="btns" style="justify-content:flex-start;">\n'
        '      <a class="btn primary" style="color:#5b3fb9;background:#e6edf3;border-color:#e6edf3;" '
        'href="https://github.com/MalekSnous/llm-diagnostic-framework#-case-studies">'
        "How to run the studies &rarr;</a>\n    </div>"
    )


def main() -> None:
    if not RESULTS.exists():
        print(f"No results directory at {RESULTS}; nothing to publish.")
        reports: dict[str, Path] = {}
    else:
        reports = _latest_reports()

    cards = []
    for key in sorted(reports):
        src = reports[key]
        dest = DOCS / src.name
        shutil.copy2(src, dest)
        cards.append(_card(_title(key), src.name))
        print(f"published {src.name}")

    inner = "\n".join(cards)
    block = f'    <div class="grid">\n{inner}\n    </div>' if cards else _empty_block()

    text = INDEX.read_text(encoding="utf-8")
    if START not in text or END not in text:
        raise SystemExit(f"Markers not found in {INDEX}; cannot inject reports.")
    new = re.sub(
        re.escape(START) + r".*?" + re.escape(END),
        f"{START}\n{block}\n    {END}",
        text,
        flags=re.DOTALL,
    )
    INDEX.write_text(new, encoding="utf-8")
    print(f"updated {INDEX} ({len(cards)} report card(s))")


if __name__ == "__main__":
    main()
